// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace CashFlow.Bdd.Tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "e2e")]
    [Xunit.TraitAttribute("Category", "auth")]
    [Xunit.TraitAttribute("Category", "bdd")]
    public partial class AutenticacaoJWTRefreshTokensELockoutE2EFeature : object, Xunit.IClassFixture<AutenticacaoJWTRefreshTokensELockoutE2EFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "e2e",
                "auth",
                "bdd"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("pt-BR"), "Features", "Autenticação JWT, refresh tokens e lockout (E2E)", "  Como sistema CashFlow\r\n  Quero proteger o login contra brute-force (lockout) e " +
                "suportar sessões longas (refresh)\r\n  Para que apenas usuários autenticados regis" +
                "trem lançamentos com UX e segurança razoáveis", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "AutenticacaoE2E.feature"
#line hidden
        
        public AutenticacaoJWTRefreshTokensELockoutE2EFeature(AutenticacaoJWTRefreshTokensELockoutE2EFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Login com credenciais válidas emite access + refresh token")]
        [Xunit.TraitAttribute("FeatureTitle", "Autenticação JWT, refresh tokens e lockout (E2E)")]
        [Xunit.TraitAttribute("Description", "Login com credenciais válidas emite access + refresh token")]
        public async global::System.Threading.Tasks.Task LoginComCredenciaisValidasEmiteAccessRefreshToken()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Login com credenciais válidas emite access + refresh token", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 8
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
    await testRunner.WhenAsync("faço POST em \"/api/v1/auth/login\" com credenciais demo válidas", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 10
    await testRunner.ThenAsync("a resposta deve ser 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 11
    await testRunner.AndAsync("a resposta deve conter um access token não vazio", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 12
    await testRunner.AndAsync("a resposta deve conter um refresh token não vazio", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 13
    await testRunner.AndAsync("a role retornada deve ser \"Merchant\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Login com senha errada retorna 401")]
        [Xunit.TraitAttribute("FeatureTitle", "Autenticação JWT, refresh tokens e lockout (E2E)")]
        [Xunit.TraitAttribute("Description", "Login com senha errada retorna 401")]
        public async global::System.Threading.Tasks.Task LoginComSenhaErradaRetorna401()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Login com senha errada retorna 401", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 15
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
    await testRunner.WhenAsync("faço POST em \"/api/v1/auth/login\" com username \"carlos\" e password \"senha-errada\"" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 17
    await testRunner.ThenAsync("a resposta deve ser 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Login com usuário inexistente retorna 401")]
        [Xunit.TraitAttribute("FeatureTitle", "Autenticação JWT, refresh tokens e lockout (E2E)")]
        [Xunit.TraitAttribute("Description", "Login com usuário inexistente retorna 401")]
        public async global::System.Threading.Tasks.Task LoginComUsuarioInexistenteRetorna401()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Login com usuário inexistente retorna 401", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 19
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 20
    await testRunner.WhenAsync("faço POST em \"/api/v1/auth/login\" com username \"fulano-inexistente\" e password \"q" +
                        "ualquer\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 21
    await testRunner.ThenAsync("a resposta deve ser 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="POST de transação sem token retorna 401")]
        [Xunit.TraitAttribute("FeatureTitle", "Autenticação JWT, refresh tokens e lockout (E2E)")]
        [Xunit.TraitAttribute("Description", "POST de transação sem token retorna 401")]
        public async global::System.Threading.Tasks.Task POSTDeTransacaoSemTokenRetorna401()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("POST de transação sem token retorna 401", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 23
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 24
    await testRunner.WhenAsync("faço POST em \"/api/v1/transactions\" sem token com payload de crédito de 100.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 25
    await testRunner.ThenAsync("a resposta deve ser 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="POST de transação com token válido retorna 201")]
        [Xunit.TraitAttribute("FeatureTitle", "Autenticação JWT, refresh tokens e lockout (E2E)")]
        [Xunit.TraitAttribute("Description", "POST de transação com token válido retorna 201")]
        public async global::System.Threading.Tasks.Task POSTDeTransacaoComTokenValidoRetorna201()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("POST de transação com token válido retorna 201", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 27
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 28
    await testRunner.GivenAsync("que estou autenticado com credenciais demo válidas", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 29
    await testRunner.WhenAsync("faço POST em \"/api/v1/transactions\" com token e payload de crédito de 150.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 30
    await testRunner.ThenAsync("a resposta deve ser 201", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 31
    await testRunner.AndAsync("o body deve conter um id de transação válido", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Conta é travada após 3 tentativas falhas consecutivas")]
        [Xunit.TraitAttribute("FeatureTitle", "Autenticação JWT, refresh tokens e lockout (E2E)")]
        [Xunit.TraitAttribute("Description", "Conta é travada após 3 tentativas falhas consecutivas")]
        [Xunit.TraitAttribute("Category", "lockout")]
        public async global::System.Threading.Tasks.Task ContaETravadaApos3TentativasFalhasConsecutivas()
        {
            string[] tagsOfScenario = new string[] {
                    "lockout"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Conta é travada após 3 tentativas falhas consecutivas", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 34
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 35
    await testRunner.WhenAsync("faço 3 tentativas de login com password \"senha-errada\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 36
    await testRunner.AndAsync("faço POST em \"/api/v1/auth/login\" com credenciais demo válidas", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 37
    await testRunner.ThenAsync("a resposta deve ser 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Refresh rotaciona o token e emite novo par")]
        [Xunit.TraitAttribute("FeatureTitle", "Autenticação JWT, refresh tokens e lockout (E2E)")]
        [Xunit.TraitAttribute("Description", "Refresh rotaciona o token e emite novo par")]
        [Xunit.TraitAttribute("Category", "refresh")]
        public async global::System.Threading.Tasks.Task RefreshRotacionaOTokenEEmiteNovoPar()
        {
            string[] tagsOfScenario = new string[] {
                    "refresh"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Refresh rotaciona o token e emite novo par", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 40
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 41
    await testRunner.GivenAsync("que estou autenticado com credenciais demo válidas", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 42
    await testRunner.WhenAsync("faço POST em \"/api/v1/auth/refresh\" com o refresh token atual", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 43
    await testRunner.ThenAsync("a resposta deve ser 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 44
    await testRunner.AndAsync("a resposta deve conter um access token não vazio", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 45
    await testRunner.AndAsync("a resposta deve conter um refresh token não vazio", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 46
    await testRunner.AndAsync("o novo refresh token deve ser diferente do anterior", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Refresh token revogado após uso (rotação) não pode ser reutilizado")]
        [Xunit.TraitAttribute("FeatureTitle", "Autenticação JWT, refresh tokens e lockout (E2E)")]
        [Xunit.TraitAttribute("Description", "Refresh token revogado após uso (rotação) não pode ser reutilizado")]
        [Xunit.TraitAttribute("Category", "refresh")]
        public async global::System.Threading.Tasks.Task RefreshTokenRevogadoAposUsoRotacaoNaoPodeSerReutilizado()
        {
            string[] tagsOfScenario = new string[] {
                    "refresh"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Refresh token revogado após uso (rotação) não pode ser reutilizado", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 49
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 50
    await testRunner.GivenAsync("que estou autenticado com credenciais demo válidas", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 51
    await testRunner.AndAsync("rotaciono o refresh token uma vez", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 52
    await testRunner.WhenAsync("faço POST em \"/api/v1/auth/refresh\" com o refresh token anterior", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 53
    await testRunner.ThenAsync("a resposta deve ser 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Logout revoga o refresh token")]
        [Xunit.TraitAttribute("FeatureTitle", "Autenticação JWT, refresh tokens e lockout (E2E)")]
        [Xunit.TraitAttribute("Description", "Logout revoga o refresh token")]
        [Xunit.TraitAttribute("Category", "refresh")]
        public async global::System.Threading.Tasks.Task LogoutRevogaORefreshToken()
        {
            string[] tagsOfScenario = new string[] {
                    "refresh"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Logout revoga o refresh token", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 56
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 57
    await testRunner.GivenAsync("que estou autenticado com credenciais demo válidas", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 58
    await testRunner.WhenAsync("faço POST em \"/api/v1/auth/logout\" com o refresh token atual", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 59
    await testRunner.ThenAsync("a resposta deve ser 204", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 60
    await testRunner.WhenAsync("faço POST em \"/api/v1/auth/refresh\" com o refresh token atual", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 61
    await testRunner.ThenAsync("a resposta deve ser 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await AutenticacaoJWTRefreshTokensELockoutE2EFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await AutenticacaoJWTRefreshTokensELockoutE2EFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
